# Generated by Django 4.0.6 on 2022-08-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_profile_indeeed_url_profile_linkedin_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='indeeed_url',
            new_name='indeed_url',
        ),
    ]
